Added Scheduler Module
micvitc/Interview-Automation-Pipeline-Scheduler pull request #1
Opened 2022-01-10 17:14 UTC by therealsgopi

Added a README for Scheduler module and also added the code for some basic scheduling (with minimum features) considering my own sample data.
Let me know your views on this update

2022-01-12 17:17 UTC, PratikGarai requested changes
Add reschedule / push back feature so single interviews can be preponed or postponed.

2022-01-12 17:59 UTC, therealsgopi commented
Noted.
Will get back to you soon.

2022-01-23 17:19 UTC, PratikGarai requested changes

2022-01-23 17:19 UTC, PratikGarai commented on Scheduler module/scheduler.py
> +schedule()
Pass dur, brk, start_date, start_time, end_time as arguments to schedule method

2022-01-23 17:19 UTC, PratikGarai commented on Scheduler module/scheduler.py
> +now = datetime.datetime.now()
calculate this inside the schedule() method

2022-01-23 17:27 UTC, therealsgopi commented on Scheduler module/scheduler.py
> +schedule()
Got it, will make it modular

2022-01-23 17:30 UTC, therealsgopi commented on Scheduler module/scheduler.py
> +now = datetime.datetime.now()
This is actually not even required, I was just experimenting something and forgot to remove it.

2022-01-24 04:21 UTC, PratikGarai commented on Scheduler module/scheduler.py
> +now = datetime.datetime.now()
okay

2022-01-24 16:00 UTC, therealsgopi commented on Scheduler module/scheduler.py
> +schedule()
Done.

2022-01-27 12:04 UTC, PratikGarai requested changes

2022-01-27 12:04 UTC, PratikGarai commented on Scheduler module/api.py
> +@scheduler.get("/schedule/duration={dur}_break={brk}_start-date={st_dt}_start-time={st_tm}_end-time={end_tm}")
Define a proper request response model using Pydantic

2022-01-27 12:05 UTC, PratikGarai requested changes

2022-01-27 12:05 UTC, PratikGarai commented on Scheduler module/scheduler.py
> +# dont think this is necessary as I will have to just scheduler in the order I get (in case rescheduled to create void etc)
keep comments less personalized, make them as generic as possible

2022-01-27 16:41 UTC, therealsgopi commented on Scheduler module/scheduler.py
> +# dont think this is necessary as I will have to just scheduler in the order I get (in case rescheduled to create void etc)
Okay bhaiya, noted. Will keep this in mind.

2022-02-06 19:37 UTC, therealsgopi commented on Scheduler module/api.py
> +@scheduler.get("/schedule/duration={dur}_break={brk}_start-date={st_dt}_start-time={st_tm}_end-time={end_tm}")
Done bhaiya, please check

2022-02-12 04:44 UTC, PratikGarai approved these changes

2022-02-12 04:44 UTC, merged